# Generated by Django 4.0.3 on 2022-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_bloglist_keyword_alter_bloglist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='blogurl',
            field=models.URLField(verbose_name='site URL'),
        ),
    ]
