# Generated by Django 4.0.3 on 2022-07-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_bloglist_blogurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
