# Generated by Django 4.0.3 on 2022-07-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_bloglist_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
